# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: NPM Install
      run: npm ci

    - name: Lint ngx-dkfds
      run: npm run lint ngx-dkfds

    - name: Test ngx-dkfds
      run: npm run test:ci ngx-dkfds

    - name: Build ngx-dkfds
      run: npm run build ngx-dkfds

    - name: NPM link ngx-dkfds
      run: |
        cd ./dist/ngx-dkfds
        npm link
        cd ../../projects/playground
        npm link ngx-dkfds

    - name: Lint playground
      run: npm run lint playground

    - name: Test playground
      run: npm run test:ci playground

    - name: Build playground
      run: npm run build playground
